version: '3'
services:
  web:
    image: basic-chatbot
    build:
      context: .
    ports:
      - 7860:7860
    volumes:
      - ~/.ai-agent-key:/home/user/.ai-agent-key
    command: "python app/server.py"
