name: chatbot
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12.8
  - pip
  - langchain=0.3.19
  - langchain-community=0.3.18
  - openai=1.64.0
  - python-dotenv=1.0.1

  - pip:
    - gradio==5.18.0
