name: chatbot
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12.8
  - pip
  - fastapi=0.115.11   # for completeness only, since this was installed due to dependency
  - langchain=0.3.19
  - langchain-community=0.3.18
  - openai=1.64.0
  - python-dotenv=1.0.1
  - uvicorn=0.34.0  # for completeness only

  - pip:
    - gradio==5.18.0
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - bcrypt==4.0.1  # Fix for "(trapped) error reading bcrypt version"
    - jinja2==3.1.2
